// import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Biniyam Beyene | Full-Stack Developer',
  description:
    "Hello, I'm Biniyam. I am a full-stack developer from Ethiopia. I enjoy building web and mobile applications. My focus is React, Next.js, and Node.js.",
  keywords: [
    'Biniyam Beyene',
    'Full-Stack Developer',
    'Ethiopia',
    'React',
    'Next.js',
    'Node.js',
    'Flutter',
    'Web development',
    'Mobile development',
    'Front-end',
    'Back-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'PostgreSQL',
    'MongoDB',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Programming',
    'Software Engineer',
    'Tech enthusiast',
  ],
  url: 'https://biniyamambachew.vercel.app',
  googleSiteVerificationId: '',
  //   url: env.SITE_URL || 'https://example.com',
  // googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
